//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ntfy_cd.rc
//
#define IDC_SETTRACK                    3
#define IDC_CATEGORIES                  3
#define IDC_INTERNET                    4
#define IDC_DBOPTIONS                   5
#define IDI_MAIN                        99
#define IDD_CDDB_OPTIONS                100
#define IDI_ICON1                       102
#define IDI_ICON2                       103
#define IDI_LOCAL                       103
#define IDI_PAUSE                       105
#define IDD_CHOOSEDISC                  105
#define IDD_ABOUT                       106
#define IDI_PLAY                        106
#define IDD_INFO                        107
#define IDD_OPTIONS                     108
#define IDI_NOAUDIO                     113
#define IDD_CDDB                        113
#define IDD_DB                          113
#define IDD_SETABSTRACKPOS              114
#define IDD_SKIP                        115
#define IDD_PROGRESS                    116
#define IDR_INTERNET                    117
#define IDR_MENU                        118
#define IDD_CATEGORYCHOOSEEXTENDED      118
#define IDD_CATEGORIES                  119
#define IDR_CONTEXT_DISC                120
#define IDB_NOTIFY                      121
#define IDD_DIALOG1                     123
#define IDD_TAB_PLAYLIST                124
#define IDD_INFO_TAB_PLAYLIST           124
#define IDD_TAB_DISCINFO                125
#define IDI_ICON3                       125
#define IDD_INFO_TAB_DISCINFO           125
#define IDI_REMOTE                      125
#define IDD_TAB_TRACKINFO               126
#define IDD_INFO_TAB_TRACKINFO          126
#define IDD_TAB_REMOTEDB                127
#define IDD_MOTD                        127
#define IDD_TAB_LOCALDB                 128
#define IDD_TAB_HTTPDB                  129
#define IDD_OPTIONS_TAB_CONTROLS        129
#define IDD_TAB_GENERAL                 130
#define IDD_CREDITS                     130
#define IDD_TAB_EMAIL                   131
#define IDR_DB                          131
#define IDD_SEARCH                      132
#define IDD_OPTIONS_TAB_GENERAL         133
#define IDD_TAB_EMPTY                   134
#define IDD_OPTIONS_TAB_TOOLTIP         135
#define IDD_OPTIONS_TAB_DATABASE        136
#define IDD_OPTIONS_TAB_LOCAL           137
#define IDD_OPTIONS_TAB_REMOTE          138
#define IDD_OPTIONS_TAB_EMAIL           139
#define IDD_OPTIONS_TAB_CATEGORIES      140
#define IDD_ASKFORPASSWORD              141
#define IDD_CATEGORYCHOOSESINGLE        142
#define IDE_PAGE                        502
#define IDE_LINE                        503
#define IDC_QUERYLOCAL                  1000
#define IDC_ARTIST                      1001
#define IDC_QUERYREMOTE                 1001
#define IDC_TRACKS                      1002
#define IDC_STORELOCAL                  1002
#define IDC_TITLE                       1003
#define IDC_VERSION                     1003
#define IDI_STOP                        1003
#define IDC_LOCALPATH                   1003
#define IDC_TRACK                       1004
#define IDC_TIME_NONE                   1004
#define IDC_LOCALTYPE                   1004
#define IDC_AUTOADDQUEUE                1004
#define IDC_TIME_TRACK                  1005
#define IDC_PLAYLIST                    1005
#define IDC_REMOTESERVER                1005
#define IDC_AUTOGETQUEUE                1005
#define IDC_AUTORETRIEVEQUEUE           1005
#define IDC_TIME_TRACKREM               1006
#define IDC_REMOTEPORT                  1006
#define IDC_TIME_CD                     1007
#define IDC_MIN                         1007
#define IDC_NOTRAYICON                  1007
#define IDC_TIME_CDREM                  1008
#define IDC_SEC                         1008
#define IDC_REMOTETIMEOUT               1008
#define IDC_STOPONEXIT                  1009
#define IDC_EMAILADDRESS                1009
#define IDC_STOPONSTART                 1010
#define IDC_EMAILSERVER                 1010
#define IDC_POLLTIME                    1011
#define IDC_STORERESULT                 1011
#define IDC_EXITONCDREMOVE              1012
#define IDC_USEHTTP                     1012
#define IDC_PROTHTTP                    1012
#define IDC_PREVALWAYSPREV              1013
#define IDC_USEPROXY                    1013
#define IDC_REMEMBERSTATUS              1014
#define IDC_HTTPSERVER                  1014
#define IDC_USEAUTHENTICATION           1014
#define IDC_ADD                         1015
#define IDC_FULLSTATUSCHECK             1015
#define IDC_NOINSERTNOTIFICATION        1015
#define IDC_PROXYSERVER                 1015
#define IDC_REMOVE                      1016
#define IDC_TRACKSMENUCOLUMN            1016
#define IDC_HTTPPATH                    1016
#define IDC_CLEAR                       1017
#define IDC_NOMENUBITMAP                1017
#define IDC_PROXYPORT                   1017
#define IDC_RESET                       1018
#define IDC_CDINFO_ARTIST               1018
#define IDC_STOREININI                  1018
#define IDC_USER                        1018
#define IDC_INSERT                      1019
#define IDC_CDINFO_TITLE                1019
#define IDC_PASSWORD                    1019
#define IDC_CDINFO_TRACKTITLE           1020
#define IDC_RANDOM                      1020
#define IDC_ASKFORPASSWORD              1020
#define IDC_CDINFO_TRACKLENGTH          1021
#define IDC_LEFT_NEXT                   1022
#define IDC_SHOWONCAPTION               1022
#define IDC_LEFT_PAUSE                  1023
#define IDC_TREE                        1023
#define IDC_USEFONT                     1023
#define IDC_LIST                        1024
#define IDC_NOMENUBREAK                 1024
#define IDC_CDINFO_TRACKNO              1024
#define IDC_LEFT_PREV                   1025
#define IDC_EXPORT                      1025
#define IDC_LEFT_STOP                   1026
#define IDC_IMPORT                      1026
#define IDC_PLAYTIME                    1026
#define IDC_REPORT                      1027
#define IDC_SELTIME                     1027
#define IDC_ARTISTINMENU                1027
#define IDC_SLIDER                      1028
#define IDC_STATISTICS                  1028
#define IDC_TIME                        1029
#define IDC_SEND                        1029
#define IDC_LEN                         1032
#define IDC_SPIN                        1033
#define IDC_DBDLL                       1036
#define IDC_COUNT                       1044
#define IDC_CATEGORY                    1047
#define IDC_CHOOSEALL                   1049
#define IDC_CURRID                      1050
#define IDC_ALIASID                     1051
#define IDC_ARTISTS                     1056
#define IDC_SETNAME                     1058
#define IDC_NAME                        1059
#define IDC_DEFAULTDEVICE               1060
#define IDC_TAB                         1064
#define IDC_PLAYLIST_STATIC             1065
#define IDC_TRACKINFO                   1067
#define IDC_DISCINFO                    1068
#define IDC_TRACKS2                     1069
#define IDC_PROTCDDB                    1071
#define IDC_USEINI                      1073
#define IDC_USECDDB                     1074
#define IDC_EDIT                        1074
#define IDC_NOMOTD                      1075
#define IDC_HOMEPAGE                    1077
#define IDC_FONT                        1079
#define IDC_TOOLTIP                     1080
#define IDC_CAPTION                     1081
#define IDC_EXTERNALCOMMAND             1081
#define IDC_BROWSE                      1082
#define IDC_PROGRESS                    1083
#define IDC_EMAIL                       1084
#define IDC_CHECKVERSION                1086
#define IDC_BUTTON1                     1087
#define IDC_SLIDER1                     1088
#define IDC_CLICK1                      1089
#define IDC_CLICK2                      1090
#define IDC_CLICK3                      1091
#define IDC_CLICK4                      1092
#define IDC_CLICK5                      1093
#define IDC_DRAGR                       1094
#define IDC_DRAGL                       1095
#define IDC_DRAGU                       1096
#define IDC_DRAGD                       1097
#define IDC_HOTKEY1                     1098
#define IDC_HOTKEY2                     1099
#define IDC_CREDITS                     1099
#define IDC_HOTKEY3                     1100
#define IDC_QUERYSITES                  1100
#define IDC_HOTKEY4                     1101
#define IDC_AUTOCHECKFORNEWVERSION      1101
#define IDC_HOTKEY5                     1102
#define IDC_HOTKEY6                     1103
#define IDC_AUTOCONNECT                 1103
#define IDC_HOTKEY7                     1104
#define IDC_CONNECTION                  1104
#define IDC_HOTKEY8                     1105
#define IDC_USEANYCONNECTION            1105
#define IDC_HOTKEY9                     1106
#define IDC_QUERYIFCONNECTED            1106
#define IDC_CLOSECONNECTION             1107
#define IDC_PROPERTIES                  1108
#define IDC_NEWCONNECTION               1109
#define IDC_USERNAME                    1110
#define IDC_FORMAT                      1113
#define IDC_EXAMPLE                     1114
#define IDC_SEARCH                      1115
#define IDC_REGISTERDEFAULT             1116
#define IDM_PLAY                        40007
#define IDM_NEXT                        40008
#define IDM_QUIT                        40009
#define IDM_ABOUT                       40010
#define IDM_PAUSE                       40011
#define IDM_STOP                        40012
#define IDM_PREV                        40013
#define IDM_INFO                        40014
#define IDM_STUFF                       40016
#define IDM_OPEN                        40017
#define IDM_OPTIONS                     40018
#define IDM_REPEAT                      40021
#define IDM_RANDOMIZE                   40022
#define IDM_CDDB                        40023
#define IDM_DB                          40023
#define IDM_SETABSTRACKPOS              40028
#define IDM_SKIP                        40029
#define IDM_REPEATTRACK                 40030
#define IDM_PLAYWHOLE                   40031
#define IDM_MAKEALIAS                   40032
#define IDM_SETCATEGORY                 40033
#define IDM_DELETE                      40034
#define IDM_CLOSE                       40037
#define IDM_INTERNETGET                 40046
#define IDM_INTERNETSEND                40047
#define IDM_SEND                        40048
#define IDM_ADDTOQUEUE                  40049
#define IDM_GETQUEUED                   40050
#define IDM_GETQUEUEDITEMS              40050
#define IDM_REMOVEQUEUEDITEMS           40051
#define ID_FILE_IMPORT                  40053
#define ID_FILE_REPORT                  40054
#define ID_FILE_STATISTICS              40055
#define ID_FILE_EXPORT                  40056
#define ID_SEARCH_ARTIST                40057
#define ID_SEARCH_TITLE                 40058
#define ID_SEARCH_TRACK                 40059
#define ID_SEARCH_FINDNEXT              40060
#define ID_VIEW_BYARTIST                40061
#define ID_VIEW_BYCATEGORY              40062
#define IDM_CDINFO                      40063

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         40064
#define _APS_NEXT_CONTROL_VALUE         1118
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
